CREATE TABLE [dbo].[SalesSmyth_Hot_Leads_RAW](
	[Scoop ID] [varchar](max) NULL,
	[Topic_name] [varchar](max) NULL,
	[Scoop Types] [varchar](max) NULL,
	[Scoop Topics] [varchar](max) NULL,
	[Scoop Description] [varchar](max) NULL,
	[Scoop Date Published] [varchar](max) NULL,
	[Scoop Date Updated] [varchar](max) NULL,
	[Scoops Updated Text] [varchar](max) NULL,
	[Scoop Url] [varchar](max) NULL,
	[Scoop Url Text] [varchar](max) NULL,
	[ZoomInfo Company ID] [varchar](max) NULL,
	[Company Name] [varchar](max) NULL,
	[Website] [varchar](max) NULL,
	[Founded Year] [varchar](max) NULL,
	[Revenue (in 000s USD)] [varchar](max) NULL,
	[Primary Industry] [varchar](max) NULL,
	[Primary Sub-Industry] [varchar](max) NULL,
	[All Industries] [varchar](max) NULL,
	[All Sub-Industries] [varchar](max) NULL,
	[Industry Hierarchical Category] [varchar](max) NULL,
	[Secondary Industry Hierarchical Category] [varchar](max) NULL,
	[Alexa Rank] [varchar](max) NULL,
	[LinkedIn Company Profile URL] [varchar](max) NULL,
	[Facebook Company Profile URL] [varchar](max) NULL,
	[Twitter Company Profile URL] [varchar](max) NULL,
	[Employees] [varchar](max) NULL,
	[Certified Active Company] [varchar](max) NULL,
	[Certification Date] [varchar](max) NULL,
	[Total Funding Amount (in 000s USD)] [varchar](max) NULL,
	[Recent Funding Amount (in 000s USD)] [varchar](max) NULL,
	[Recent Funding Round] [varchar](max) NULL,
	[Recent Funding Date] [varchar](max) NULL,
	[Recent Investors] [varchar](max) NULL,
	[All Investors] [varchar](max) NULL,
	[ZoomInfo Contact ID] [varchar](max) NULL,
	[Last Name] [varchar](max) NULL,
	[First Name] [varchar](max) NULL,
	[Email Address] [varchar](max) NULL,
	[Job Title] [varchar](max) NULL,
	[Seniority] [varchar](max) NULL,
	[Direct Phone Number] [varchar](max) NULL,
	[LinkedIn Contact Profile URL] [varchar](max) NULL,
	[Company Street Address] [varchar](max) NULL,
	[Company City] [varchar](max) NULL,
	[Company State] [varchar](max) NULL,
	[Company Zip Code] [varchar](max) NULL,
	[Company Country] [varchar](max) NULL,
	[Full Address] [varchar](max) NULL,
	[Number of Locations] [varchar](max) NULL,
	[Query Name] [varchar](max) NULL
)