CREATE TABLE [dbo].[SalesSmyth_Products_Data_Raw](
	[ZoomInfo Company ID] [varchar](max) NULL,
	[Product_Type] [varchar](max) NULL,
	[Company Name] [varchar](max) NULL,
	[Website] [varchar](max) NULL,
	[Founded Year] [varchar](max) NULL,
	[Company HQ Phone] [varchar](max) NULL,
	[Fax] [varchar](max) NULL,
	[Ticker] [varchar](max) NULL,
	[Revenue (in 000s USD)] [varchar](max) NULL,
	[Revenue Range (in USD)] [varchar](max) NULL,
	[Employees] [varchar](max) NULL,
	[Employee Range] [varchar](max) NULL,
	[SIC Code 1] [varchar](max) NULL,
	[SIC Code 2] [varchar](max) NULL,
	[SIC Codes] [varchar](max) NULL,
	[NAICS Code 1] [varchar](max) NULL,
	[NAICS Code 2] [varchar](max) NULL,
	[NAICS Codes] [varchar](max) NULL,
	[Primary Industry] [varchar](max) NULL,
	[Primary Sub-Industry] [varchar](max) NULL,
	[All Industries] [varchar](max) NULL,
	[All Sub-Industries] [varchar](max) NULL,
	[Industry Hierarchical Category] [varchar](max) NULL,
	[Secondary Industry Hierarchical Category] [varchar](max) NULL,
	[Alexa Rank] [varchar](max) NULL,
	[ZoomInfo Company Profile URL] [varchar](max) NULL,
	[LinkedIn Company Profile URL] [varchar](max) NULL,
	[Facebook Company Profile URL] [varchar](max) NULL,
	[Twitter Company Profile URL] [varchar](max) NULL,
	[Ownership Type] [varchar](max) NULL,
	[Business Model] [varchar](max) NULL,
	[Certified Active Company] [varchar](max) NULL,
	[Certification Date] [varchar](max) NULL,
	[Total Funding Amount (in 000s USD)] [varchar](max) NULL,
	[Recent Funding Amount (in 000s USD)] [varchar](max) NULL,
	[Recent Funding Round] [varchar](max) NULL,
	[Recent Funding Date] [varchar](max) NULL,
	[Recent Investors] [varchar](max) NULL,
	[All Investors] [varchar](max) NULL,
	[Company Street Address] [varchar](max) NULL,
	[Company City] [varchar](max) NULL,
	[Company State] [varchar](max) NULL,
	[Company Zip Code] [varchar](max) NULL,
	[Company Country] [varchar](max) NULL,
	[Full Address] [varchar](max) NULL,
	[Number of Locations] [varchar](max) NULL,
	[Company Is Acquired] [varchar](max) NULL,
	[Company ID (Ultimate Parent)] [varchar](max) NULL,
	[Entity Name (Ultimate Parent)] [varchar](max) NULL,
	[Company ID (Immediate Parent)] [varchar](max) NULL,
	[Entity Name (Immediate Parent)] [varchar](max) NULL,
	[Relationship (Immediate Parent)] [varchar](max) NULL,
	[Query Name] [varchar](max) NULL
) 